version: '2'
services:

  web:
    image: ansible/awx_web:11.2.0
    container_name: awx_web
    depends_on:
      - redis
      - memcached
      - postgres
    ports:
      - "80:8052"
    hostname: awxweb
    user: root
    restart: unless-stopped
    volumes:
      - "./SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./environment.sh:/etc/tower/conf.d/environment.sh"
      - "./credentials.py:/etc/tower/conf.d/credentials.py"
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/awx_11/projects:/var/lib/awx/projects:rw"
      - "/etc/localtime:/etc/localtime:ro"

  task:
    image: ansible/awx_task:11.2.0
    container_name: awx_task
    depends_on:
      - redis
      - memcached
      - web
      - postgres
    hostname: awx
    user: root
    restart: unless-stopped
    volumes:
      - "./SECRET_KEY:/etc/tower/SECRET_KEY"
      - "./environment.sh:/etc/tower/conf.d/environment.sh"
      - "./credentials.py:/etc/tower/conf.d/credentials.py"
      - "/awx_11/projects:/var/lib/awx/projects:rw"
      - "/etc/localtime:/etc/localtime:ro"
      
  redis:
    image: redis
    container_name: awx_redis
    restart: unless-stopped

  memcached:
    image: "memcached:alpine"
    container_name: awx_memcached
    restart: unless-stopped

  postgres:
    image: postgres:10
    container_name: awx_postgres
    restart: unless-stopped
    volumes:
      - /awx_11/postgres/10/data/:/var/lib/postgresql/data/pgdata:Z
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
      PGDATA: /var/lib/postgresql/data/pgdata
